C     Diagram 1
      DATA MAPCONFIG(1)/1/
      DATA (IFOREST(I,-1,1),I=1,2)/6,5/
      DATA (SPROP(I,-1,1),I=1,2)/23,23/
      DATA TPRID(-1,1)/0/
      DATA (IFOREST(I,-2,1),I=1,2)/4,3/
      DATA (SPROP(I,-2,1),I=1,2)/23,23/
      DATA TPRID(-2,1)/0/
      DATA (IFOREST(I,-3,1),I=1,2)/-1,-2/
      DATA (SPROP(I,-3,1),I=1,2)/25,25/
      DATA TPRID(-3,1)/0/
      DATA (IFOREST(I,-4,1),I=1,2)/7,-3/
      DATA (SPROP(I,-4,1),I=1,2)/21,21/
      DATA TPRID(-4,1)/0/
C     Diagram 2
      DATA MAPCONFIG(2)/2/
      DATA (IFOREST(I,-1,2),I=1,2)/6,5/
      DATA (SPROP(I,-1,2),I=1,2)/23,23/
      DATA TPRID(-1,2)/0/
      DATA (IFOREST(I,-2,2),I=1,2)/4,3/
      DATA (SPROP(I,-2,2),I=1,2)/23,23/
      DATA TPRID(-2,2)/0/
      DATA (IFOREST(I,-3,2),I=1,2)/-1,-2/
      DATA (SPROP(I,-3,2),I=1,2)/25,25/
      DATA TPRID(-3,2)/0/
      DATA (IFOREST(I,-4,2),I=1,2)/1,-3/
      DATA TPRID(-4,2)/21/
      DATA (SPROP(I,-4,2),I=1,2)/0,0/
      DATA (IFOREST(I,-5,2),I=1,2)/-4,7/
C     Diagram 3
      DATA MAPCONFIG(3)/3/
      DATA (IFOREST(I,-1,3),I=1,2)/6,5/
      DATA (SPROP(I,-1,3),I=1,2)/23,23/
      DATA TPRID(-1,3)/0/
      DATA (IFOREST(I,-2,3),I=1,2)/4,3/
      DATA (SPROP(I,-2,3),I=1,2)/23,23/
      DATA TPRID(-2,3)/0/
      DATA (IFOREST(I,-3,3),I=1,2)/-1,-2/
      DATA (SPROP(I,-3,3),I=1,2)/25,25/
      DATA TPRID(-3,3)/0/
      DATA (IFOREST(I,-4,3),I=1,2)/1,7/
      DATA TPRID(-4,3)/21/
      DATA (SPROP(I,-4,3),I=1,2)/0,0/
      DATA (IFOREST(I,-5,3),I=1,2)/-4,-3/
C     Number of configs
      DATA MAPCONFIG(0)/3/
